# Generated by Django 2.1.2 on 2018-10-27 17:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPhotoGallery', '0002_zpgcloudfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zpgcloudfile',
            old_name='minme_type',
            new_name='mime_type',
        ),
    ]
