# Generated by Django 2.1.2 on 2018-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPhotoGallery', '0003_auto_20181027_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpgcloudfile',
            name='hash',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
